---
build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.21
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
labels:
  org.opencontainers.image.title: Uptime Kuma
  org.opencontainers.image.description: Self-hosted uptime monitoring tool
  org.opencontainers.image.source: https://github.com/adrianoamalfi/hassos-apps
  org.opencontainers.image.licenses: MIT
