---
name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yaml

  lint-addon:
    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ${{ fromJson(needs.detect-changes.outputs.addons) }}
    steps:
      - uses: actions/checkout@v6
      - name: Lint ${{ matrix.addon }}
        uses: frenck/action-addon-linter@v2
        with:
          path: "./${{ matrix.addon }}"

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                max: 150
              truthy:
                check-keys: false

  lint-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "."

  lint-hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          recursive: true
          ignore: DL3018
